const statistics = [
  {
    pincode: "123456",
    district: "Example District",
    centerName: "Example District PHC",
    feeType: "Free",
    stateName: "Some State",
    vaccine: "Covishield",
    ageLimit: "18+",
    slot: "10 slots",
  },
  {
    pincode: "654321",
    district: "Another District",
    centerName: "Another District AIMS",
    feeType: "Paid",
    stateName: "Another State",
    vaccine: "Covaxin",
    ageLimit: "45+",
    slot: "15 slots",
  },
  {
    pincode: "789012",
    district: "Third District",
    centerName: "Third District Clinic",
    feeType: "Free",
    stateName: "Third State",
    vaccine: "Sputnik V",
    ageLimit: "18+",
    slot: "20 slots",
  },
  {
    pincode: "345678",
    district: "Fourth District",
    centerName: "Fourth District Hospital",
    feeType: "Paid",
    stateName: "Fourth State",
    vaccine: "Moderna",
    ageLimit: "60+",
    slot: "5 slots",
  },
  {
    pincode: "901234",
    district: "Fifth District",
    centerName: "Fifth District Health Unit",
    feeType: "Free",
    stateName: "Fifth State",
    vaccine: "Pfizer",
    ageLimit: "12+",
    slot: "30 slots",
  },
  {
    pincode: "567890",
    district: "Sixth District",
    centerName: "Sixth District Wellness Center",
    feeType: "Paid",
    stateName: "Sixth State",
    vaccine: "Johnson & Johnson",
    ageLimit: "18+",
    slot: "25 slots",
  },
  {
    pincode: "112233",
    district: "Seventh District",
    centerName: "Seventh District Medical Center",
    feeType: "Free",
    stateName: "Seventh State",
    vaccine: "Novavax",
    ageLimit: "30+",
    slot: "12 slots",
  },
  {
    pincode: "223344",
    district: "Eighth District",
    centerName: "Eighth District Health Facility",
    feeType: "Paid",
    stateName: "Eighth State",
    vaccine: "Sinovac",
    ageLimit: "50+",
    slot: "8 slots",
  },
  {
    pincode: "334455",
    district: "Ninth District",
    centerName: "Ninth District Clinic",
    feeType: "Free",
    stateName: "Ninth State",
    vaccine: "Sinopharm",
    ageLimit: "18+",
    slot: "16 slots",
  },
  {
    pincode: "445566",
    district: "Tenth District",
    centerName: "Tenth District Hospital",
    feeType: "Paid",
    stateName: "Tenth State",
    vaccine: "AstraZeneca",
    ageLimit: "65+",
    slot: "9 slots",
  },
  {
    pincode: "556677",
    district: "Eleventh District",
    centerName: "Eleventh District PHC",
    feeType: "Free",
    stateName: "Eleventh State",
    vaccine: "Covishield",
    ageLimit: "18+",
    slot: "14 slots",
  },
  {
    pincode: "667788",
    district: "Twelfth District",
    centerName: "Twelfth District AIMS",
    feeType: "Paid",
    stateName: "Twelfth State",
    vaccine: "Covaxin",
    ageLimit: "45+",
    slot: "17 slots",
  },
  {
    pincode: "778899",
    district: "Thirteenth District",
    centerName: "Thirteenth District Clinic",
    feeType: "Free",
    stateName: "Thirteenth State",
    vaccine: "Sputnik V",
    ageLimit: "18+",
    slot: "22 slots",
  },
  {
    pincode: "889900",
    district: "Fourteenth District",
    centerName: "Fourteenth District Hospital",
    feeType: "Paid",
    stateName: "Fourteenth State",
    vaccine: "Moderna",
    ageLimit: "60+",
    slot: "11 slots",
  },
  {
    pincode: "990011",
    district: "Fifteenth District",
    centerName: "Fifteenth District Health Unit",
    feeType: "Free",
    stateName: "Fifteenth State",
    vaccine: "Pfizer",
    ageLimit: "12+",
    slot: "28 slots",
  },
  {
    pincode: "000122",
    district: "Sixteenth District",
    centerName: "Sixteenth District Wellness Center",
    feeType: "Paid",
    stateName: "Sixteenth State",
    vaccine: "Johnson & Johnson",
    ageLimit: "18+",
    slot: "26 slots",
  },
  {
    pincode: "123123",
    district: "Seventeenth District",
    centerName: "Seventeenth District Medical Center",
    feeType: "Free",
    stateName: "Seventeenth State",
    vaccine: "Novavax",
    ageLimit: "30+",
    slot: "13 slots",
  },
  {
    pincode: "321321",
    district: "Eighteenth District",
    centerName: "Eighteenth District Health Facility",
    feeType: "Paid",
    stateName: "Eighteenth State",
    vaccine: "Sinovac",
    ageLimit: "50+",
    slot: "10 slots",
  },
  {
    pincode: "432432",
    district: "Nineteenth District",
    centerName: "Nineteenth District Clinic",
    feeType: "Free",
    stateName: "Nineteenth State",
    vaccine: "Sinopharm",
    ageLimit: "18+",
    slot: "18 slots",
  },
  {
    pincode: "543543",
    district: "Twentieth District",
    centerName: "Twentieth District Hospital",
    feeType: "Paid",
    stateName: "Twentieth State",
    vaccine: "AstraZeneca",
    ageLimit: "65+",
    slot: "7 slots",
  },
];

module.exports = { statistics };
